name: Minimal Hello World Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Test 1: Basic container and tools
  test-container:
    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:v3.0-branch

    steps:
    - name: Test basic commands
      run: |
        echo "=== Testing Basic Environment ==="
        echo "Current directory: $(pwd)"
        echo "Current user: $(whoami)"
        echo "Available disk space:"
        df -h
        
        echo "=== Testing Required Tools ==="
        which west || echo "west not found"
        which arm-none-eabi-gcc || echo "arm-none-eabi-gcc not found"
        which cmake || echo "cmake not found"
        which ninja || echo "ninja not found"
        
        echo "=== Tool Versions ==="
        west --version 2>/dev/null || echo "west version failed"
        arm-none-eabi-gcc --version 2>/dev/null | head -1 || echo "gcc version failed"
        cmake --version 2>/dev/null | head -1 || echo "cmake version failed"

  # Test 2: Simple checkout
  test-checkout:
    runs-on: ubuntu-latest
    needs: test-container
    container:
      image: nordicplayground/nrfconnect-sdk:v3.0-branch

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check repository contents
      run: |
        echo "=== Repository Contents ==="
        ls -la
        echo "Current directory: $(pwd)"
        echo "Git status:"
        git status || echo "Not a git repository or git not available"

  # Test 3: Initialize minimal west workspace
  test-west-init:
    runs-on: ubuntu-latest
    needs: test-checkout
    container:
      image: nordicplayground/nrfconnect-sdk:v3.0-branch

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: my-project

    - name: Create minimal west.yml
      run: |
        echo "=== Creating Minimal West Manifest ==="
        cd my-project
        
        # Create a minimal west.yml for testing
        mkdir -p .west
        cat > west.yml << 'WESTEOF'
        manifest:
          self:
            path: .
          
          remotes:
            - name: zephyr
              url-base: https://github.com/zephyrproject-rtos
          
          projects:
            - name: zephyr
              remote: zephyr
              revision: v3.4.0
              path: zephyr
              import: true
        WESTEOF
        
        echo "West manifest created:"
        cat west.yml

    - name: Initialize west workspace
      run: |
        echo "=== Initializing West Workspace ==="
        cd my-project
        west init -l .
        echo "West initialization complete"
        
        echo "=== West Status ==="
        west list || echo "West list failed"

  # Test 4: Update workspace (this might take time)
  test-west-update:
    runs-on: ubuntu-latest
    needs: test-west-init
    container:
      image: nordicplayground/nrfconnect-sdk:v3.0-branch

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: my-project

    - name: Create minimal west.yml
      run: |
        cd my-project
        cat > west.yml << 'WESTEOF'
        manifest:
          self:
            path: .
          
          remotes:
            - name: zephyr
              url-base: https://github.com/zephyrproject-rtos
          
          projects:
            - name: zephyr
              remote: zephyr
              revision: v3.4.0
              path: zephyr
              import: true
        WESTEOF

    - name: Initialize and update workspace
      run: |
        echo "=== Initializing West Workspace ==="
        cd my-project
        west init -l .
        
        echo "=== Updating Workspace (this may take a few minutes) ==="
        west update --narrow -o=--depth=1
        
        echo "=== Workspace Contents ==="
        ls -la
        ls -la zephyr/ || echo "Zephyr directory not found"

  # Test 5: Build hello world sample
  test-hello-world:
    runs-on: ubuntu-latest
    needs: test-west-update
    container:
      image: nordicplayground/nrfconnect-sdk:v3.0-branch

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: my-project

    - name: Setup workspace
      run: |
        cd my-project
        cat > west.yml << 'WESTEOF'
        manifest:
          self:
            path: .
          
          remotes:
            - name: zephyr
              url-base: https://github.com/zephyrproject-rtos
          
          projects:
            - name: zephyr
              remote: zephyr
              revision: v3.4.0
              path: zephyr
              import: true
        WESTEOF
        
        west init -l .
        west update --narrow -o=--depth=1

    - name: Build hello world
      run: |
        echo "=== Setting up Zephyr Environment ==="
        cd my-project
        source zephyr/zephyr-env.sh
        
        echo "=== Building Hello World Sample ==="
        west build -b qemu_x86 zephyr/samples/hello_world
        
        echo "=== Build Success! ==="
        echo "Build artifacts:"
        ls -la build/zephyr/
        
        echo "Binary size:"
        ls -lh build/zephyr/zephyr.elf

    - name: Upload hello world artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello-world-qemu
        path: my-project/build/zephyr/zephyr.elf