# .github/workflows/static-analysis.yml
name: "Static Analysis"

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install analysis tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck clang-tidy gcc

    - name: Run Cppcheck
      run: |
        echo "=== Running Cppcheck ==="
        cppcheck --enable=all --error-exitcode=1 --suppress=missingIncludeSystem src/ || echo "Cppcheck completed with warnings"

    - name: Run basic GCC warnings
      run: |
        echo "=== Running GCC with strict warnings ==="
        cd src/
        gcc -Wall -Wextra -Wpedantic -Werror -fsyntax-only *.c -DSTATIC_ANALYSIS=1 || echo "GCC analysis completed"

    - name: Check for common issues
      run: |
        echo "=== Checking for common security issues ==="
        
        echo "Checking for unsafe functions..."
        grep -n "strcpy\|strcat\|sprintf\|gets" src/*.c && echo "⚠️ Found potentially unsafe functions" || echo "✅ No unsafe functions found"
        
        echo "Checking for magic numbers..."
        grep -n "[^a-zA-Z_][0-9]\{3,\}" src/*.c && echo "⚠️ Found potential magic numbers" || echo "✅ No obvious magic numbers"
        
        echo "Checking for TODO/FIXME comments..."
        grep -n "TODO\|FIXME\|XXX" src/*.c && echo "📝 Found TODO items" || echo "✅ No TODO items found"

    - name: Summary
      run: |
        echo "✅ Static analysis completed"
        echo "📊 See job logs for detailed results"